# Generated by Django 5.0.6 on 2024-05-13 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherregistration',
            name='date_of_application',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='teacherregistration',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacherregistration',
            name='gender',
            field=models.CharField(default='', max_length=255),
        ),
    ]
