# Generated by Django 5.0.6 on 2024-05-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherregistration',
            name='subjects',
            field=models.CharField(default='', max_length=255),
        ),
    ]
