# Generated by Django 5.0.6 on 2024-05-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studentfeebalance_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeebalance',
            name='term',
        ),
    ]
