# Generated by Django 5.0.6 on 2024-05-12 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_teacherregistration_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentregistration')),
            ],
        ),
    ]
