# Generated by Django 5.0.6 on 2024-05-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_amount_studentfeebalance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeebalance',
            name='amountPaid',
            field=models.IntegerField(default=''),
        ),
    ]
